#!/bin/bash


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir

#Run blockMesh
runApplication blockMesh

# Compute the wave parameters
runApplication setWaveParameters

# Define relaxation zones (only needed if you want to visualize the resulting layout)
runApplication relaxationZoneLayout

# Set application name
application="mpirun --oversubscribe -np 16 waveDyMFoam -parallel"

# Set the alpha field
runApplication setFields

# Prepare for parallelisation
runApplication decomposePar

# Run the application
runApplication $application

# Recontruct case
runApplication reconstructPar

# Reconstruct logs
runApplication foamLog log.mpirun
