#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir

#Run blockMesh
runApplication blockMesh

#Run snappyMesh
runApplication snappyHexMesh -overwrite

# Run topoSet
runApplication topoSet

# copy "points" file from 0/polyMesh to constant/polyMesh
cp -fr 0/polyMesh/points constant/polyMesh/points