#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Recontruct case
runApplication reconstructPar

# Reconstruct logs
runApplication foamLog log.pimpleFoam

# Compute Q criteria
runApplication postProcess -func Q
runApplication postProcess -func vorticity

#Extract turbine geometry
./ALgeometry.sh

#Extract probes data
cat postProcessing/crosswind/*/data_p.xy >> p_crosswind.dat
cat postProcessing/crosswind/*/data_U.xy >> U_crosswind.dat

cd postProcessing/crosswind/
find . -mindepth 1 -maxdepth 1 -name '*' -type d -printf '%f\n' | sort -n> times.dat
mv times.dat ../../times.dat