#!/bin/bash


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

nProc=$(getNumberOfProcessors)

# Set solver name

solver="mpirun --oversubscribe -np $nProc pimpleFoam -parallel"

# Run the solver
runApplication $solver
mv log.mpirun log.pimpleFoam